name: FinTech Digest Daily Run

on:
  schedule:
    # Runs at 6:00 AM EST (11:00 UTC) daily
    - cron: '0 11 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-digest:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run FinTech Digest
      env:
        GOOGLE_SEARCH_API_KEY: ${{ secrets.GOOGLE_SEARCH_API_KEY }}
        GOOGLE_SEARCH_ENGINE_ID: ${{ secrets.GOOGLE_SEARCH_ENGINE_ID }}
        LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
        RELEVANCE_THRESHOLD: ${{ vars.RELEVANCE_THRESHOLD || '0.58' }}
        MAX_EMAIL_ARTICLES: ${{ vars.MAX_EMAIL_ARTICLES || '25' }}
        SEMANTIC_TOTAL_LIMIT: ${{ vars.SEMANTIC_TOTAL_LIMIT || '60' }}
        LLM_INTEGRATION_ENABLED: ${{ vars.LLM_INTEGRATION_ENABLED || '1' }}
        SEMANTIC_SCORING_ENABLED: ${{ vars.SEMANTIC_SCORING_ENABLED || '1' }}
        DATABASE_PATH: ":memory:"
        LOG_LEVEL: INFO
        TZ: America/New_York
      run: |
        echo "Starting FinTech Digest at $(date)"
        python fintech_digest.py --verbose
        echo "Digest completed at $(date)"
        
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: digest-logs-${{ github.run_number }}
        path: fintech_digest.log
        retention-days: 7
